Import( 'project' )
Import( 'libs' )

project.StaticLibrary( 'vfwavelib',
                       sources   = project.scanFiles( ['src'] ),
                       includes  = ['src'],
                       libraries = [
                                    ],
                       shared = False
                      )

