Import( 'project', 'libs' )

project.UnitTest(
    target = project.getDirs([-1]),
    dirs = ['.'],
    includes = ['../'],
    libraries = [
        libs.judy,
        libs.judymatch,
        libs.boost,
        libs.boost_math,
        libs.boost_unit_test_framework,
    ]
)

